# config.toml

[app]
secret_key = "your-secret-key"
session_cookie_secure = true
session_cookie_httponly = true
session_cookie_samesite = "Lax"

[[oauth_providers]]
name = "google"
client_id = "YOUR_GOOGLE_CLIENT_ID"
client_secret = "YOUR_GOOGLE_CLIENT_SECRET"
authorize_url = "https://accounts.google.com/o/oauth2/auth"
access_token_url = "https://accounts.google.com/o/oauth2/token"
api_base_url = "https://www.googleapis.com/oauth2/v1/"
client_kwargs = { scope = "openid email profile" }
label = "Sign in with Google"
image_url = "https://developers.google.com/identity/images/g-logo.png"

[[oauth_providers]]
name = "microsoft"
client_id = "YOUR_MICROSOFT_CLIENT_ID"
client_secret = "YOUR_MICROSOFT_CLIENT_SECRET"
authorize_url = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize"
access_token_url = "https://login.microsoftonline.com/common/oauth2/v2.0/token"
api_base_url = "https://graph.microsoft.com/v1.0/"
client_kwargs = { scope = "User.Read" }
label = "Sign in with Microsoft"
image_url = "https://login.live.com/images/microsoft_logo.png"

# Add more providers as needed
