version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/app
      - ./nginx/proxies:/etc/nginx/conf.d/proxies
    environment:
      SECRET_KEY: your-secret-key
    ports:
      - "5001:5000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxies:/etc/nginx/conf.d/proxies
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
