services:
  app:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./avauth-proxy/nginx_templates:/app/avauth-proxy/nginx_templates
      - ./nginx/proxies:/etc/nginx/conf.d/proxies
      - ./proxies_config.toml:/app/proxies_config.toml
      - ./config.toml:/app/config.toml
    environment:
      SECRET_KEY: your-secret-key
    ports:
      - "5000:5000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxies:/etc/nginx/conf.d/proxies
    ports:
      - "80:80"
