services:
  app:
    build: .
    #command: ["pytest"]
    command: tail -f /dev/null
    environment:
      FLASK_ENV: testing
      CONFIG_TOML_FILE: /app/avauth_proxy/tests/config_test.toml
      SECRET_KEY: "test-secret-key"
    volumes:
      - .:/app
    depends_on:
      - mock_oauth2_server
    networks:
      - test_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 6

  mock_oauth2_server:
    build:
      context: .
      dockerfile: Dockerfile.mock_oauth
    environment:
      AUTHLIB_INSECURE_TRANSPORT: "1"
    ports:
      - "6000:6000"
    networks:
      - test_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/health"]
      interval: 10s
      timeout: 5s
      retries: 6

networks:
  test_network:
    driver: bridge
