services:
  app:
    build: .
    volumes:
      - .:/app
      - ./nginx/proxies:/etc/nginx/conf.d/proxies
    environment:
      SECRET_KEY: your-secret-key
    ports:
      - "5000:5000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxies:/etc/nginx/conf.d/proxies
    ports:
      - "80:80"
